name: Build Binaries

# Controls when the workflow will run
on: 
  push:
    tags:
    - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: .  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checkout the repository code and get packages.
      - name: Setup Checkout 
        uses: actions/checkout@v3


      # setup go
      - name: Setup Golang Action
        uses: actions/setup-go@v5.0.0 


      - name: Build Binaries
        run: |   
         cd cmd
         GOOS=linux GOARCH=arm64 go build -o dynu-arm64 .
         

      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "cmd/dynu-arm64"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: realease-binary
          path: cmd/
